%I=imread('sample1.jpeg');
I=imread('shadow1.jpg');
%I=imread('shadow2.jpg');
figure, imshow(I);
res2=imread('I.jpg');
I=im2double(I);
img=rgb2gray(I);
figure, imshow(img);
size(img);
mask = zeros(size(img));
%maskedRgbImage = bsxfun(@times, rgbImage, cast(~mask, 'like', rgbImage));
mask(25:end-25,25:end-25) = 2;
maskimg=activecontour(img,mask,600);
figure, imshow(maskimg);
maskimg=im2uint8(maskimg);
maskimg=imcomplement(maskimg);
imshow(maskimg);
maskimg=im2double(maskimg);
channel1 = maskimg(:,:,1);
channel2 = maskimg(:,:,1);
channel3 = maskimg(:,:,1);
actualImg = cat(3,channel1,channel2,channel3);
figure, imshow(actualImg);
res=imadd(I,actualImg);
figure, imshow(res);
res1=rgb2lab(res);
figure, imshow(res1);
res1=imadd(I,res);
figure, imshow(res1);
g = histeq(res2);
figure, imshow(g);